version: '2'

services:
  postgres:
    image: 'postgres:12.0-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    # env_file:
    #   - '.env'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:5.0.6'
    command: redis-server
    volumes:
      - 'redis:/data'
    ports:
      - '6379:6379'

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/app'
    environment:
      - JOB_WORKER_URL=redis://redis:6379/0
      - RAILS_ENV=development

  # website:
  #   depends_on:
  #     - 'postgres'
  #     - 'sidekiq'
  #   build: .
  #   command: rails server -b 0.0.0.0 -p 3000
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - '.:/app'
  #   env_file:
  #     - '.env'

volumes:
  redis:
  postgres: